services:
  - type: web
    name: PhilHarvest-Staticfrontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://philharvest.onrender.com
      - key: VITE_EDI_AUTH_TOKEN
        value: master_api_key_secret_123456
