services:
  - type: web
    name: PhilHarvest
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: PhilHarvest
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d866n16gvqtc73ee49og-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: philharvest
      - key: DB_USERNAME
        value: admin
      - key: DB_PASSWORD
        value: Q3iYcq6l2pXl18rGdkJeqwTM2UTGQZVM
      - key: QUEUE_CONNECTION
        value: sqs
      - key: AWS_REGION
        value: ap-southeast-1
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: SQS_PREFIX
        sync: false
      - key: SQS_QUEUE
        value: philharvest-queue
      - key: LAMBDA_SECRET
        sync: false
      - key: EDI_AUTH_TOKEN
        value: test_token_here

  # Redis is now optional and only needed if you want cache/session storage.
  # Uncomment if required:
  # - type: redis
  #   name: redis
  #   version: "7"
  #   plan: free
  #   region: singapore