<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        if (Schema::getConnection()->getDriverName() !== 'pgsql') {
            return;
        }

        // Drop any CHECK constraint on the status column so it accepts all status values
        // (SENT, FAILED, RETRYING, etc.) not just the original enum set.
        // The constraint name is auto-generated by PostgreSQL; query for it dynamically.
        $constraints = DB::select("
            SELECT conname FROM pg_constraint
            WHERE conrelid = 'edi_transactions'::regclass
              AND contype = 'c'
              AND pg_get_constraintdef(oid) ILIKE '%status%'
        ");

        foreach ($constraints as $constraint) {
            DB::statement('ALTER TABLE edi_transactions DROP CONSTRAINT IF EXISTS "' . $constraint->conname . '"');
        }
    }

    public function down(): void {}
};
